# 201 Torch and Numpy

In [1]:
import torch
import numpy as np

In [6]:
# convert numpy to tensor or vise versa
np_data = np.arange(6).reshape((2, 3))
#torch_data = torch.from_numpy(np_data)
torch_data = torch.tensor(np_data)
tensor2array = torch_data.numpy()
print(
    '\nnumpy array:\n', np_data,          # [[0 1 2], [3 4 5]]
    '\ntorch tensor:\n', torch_data,      #  0  1  2 \n 3  4  5    [torch.LongTensor of size 2x3]
    '\ntensor to array:\n', tensor2array, # [[0 1 2], [3 4 5]]
    sep="",
)


numpy array:
[[0 1 2]
 [3 4 5]]
torch tensor:
tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32)
tensor to array:
[[0 1 2]
 [3 4 5]]


In [13]:
tensor.abs()

AttributeError: 'Tensor' object has no attribute 'torch'

In [14]:
torch.FloatTensor(2,3) #构建一个2*3 Float类型的张量
torch.DoubleTensor(2,3) #构建一个2*3 Double类型的张量
torch.ByteTensor(2,3) #构建一个2*3 Byte类型的张量
torch.CharTensor(2,3) #构建一个2*3 Char类型的张量
torch.ShortTensor(2,3) #构建一个2*3 Short类型的张量
torch.IntTensor(2,3) #构建一个2*3 Int类型的张量
torch.LongTensor(2,3) #构建一个2*3 Long类型的张量

tensor([[0, 0, 0],
        [0, 0, 0]])

In [15]:
# sin
print(
    '\nsin',
    '\nnumpy: ', np.sin(data),      # [-0.84147098 -0.90929743  0.84147098  0.90929743]
    '\ntorch: ', torch.sin(tensor)  # [-0.8415 -0.9093  0.8415  0.9093]
)


sin 
numpy:  [-0.84147098 -0.90929743  0.84147098  0.90929743] 
torch:  tensor([-0.8415, -0.9093,  0.8415,  0.9093])


In [16]:
tensor.sigmoid()

tensor([0.2689, 0.1192, 0.7311, 0.8808])

In [14]:
tensor.exp()

tensor([0.3679, 0.1353, 2.7183, 7.3891])

In [15]:
# mean
print(
    '\nmean',
    '\nnumpy: ', np.mean(data),         # 0.0
    '\ntorch: ', torch.mean(tensor)     # 0.0
)


mean 
numpy:  0.0 
torch:  tensor(0.)


In [16]:
# matrix multiplication矩阵乘法
data = [[1,2], [3,4]]
tensor = torch.FloatTensor(data)  # 32-bit floating point
# correct method
print(
    '\nmatrix multiplication (matmul)',
    '\nnumpy: ', np.matmul(data, data),     # [[7, 10], [15, 22]]
    '\ntorch: ', torch.mm(tensor, tensor)   # [[7, 10], [15, 22]]
)


matrix multiplication (matmul) 
numpy:  [[ 7 10]
 [15 22]] 
torch:  tensor([[ 7., 10.],
        [15., 22.]])
